### ISSUE TITLE
Is This Repository Different From FeatureAttack Project?

### ISSUE THREAD

**Issue by ndb796** [Line290/FL-PGD#1]
Hi, thanks for sharing an interesting project.
I have seen your FeatureAttack project that uses feature distance minimization before 3 months ago.
Looking at this repository's source code, I think this repository also seems to create an adversarial example by minimizing the cosine distance at the feature level.
Is this repository different from the FeatureAttack project?

**Comment by Line290** [comment]
Hi @ndb796, I'm glad you are interested in my work. 
It's almost same as FeatureAttack. I submitted a short paper to a journal in Chinese in order to meet requirement for publications. 
This repository is for reviewers. Please ignore it. Thanks.
